name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - name: Run a one-line script
        run: node -e 'console.log(require("os").cpus().length)'
